// Generated from the SPRAWL challenge coin artwork: the inner disc sampled into a 120x60 grid of 5x10 cells.
// Each tint letter colors the character above it: c = cyan trace, p = magenta inlay, 1-3 = grey relief.
export const LIBERTY_CHARS = [
  '',
  '                                                 .::++++++:  :+++++++:.',
  '                                         .::+++:++++++++++    ++++++++++++++++.',
  '                                    .::++++++++++++++++++: .  +++++++++++++++++++++:',
  '                                .++++++::::::::.........   ||   . .......:::+++++++++++:',
  '                             . :+++:::::....        .      ||      .       ...:::+++++++:.',
  '                          :++  \\\\.+::...                   ##      .            ...::: +// ++:',
  '                       .:++++:  \\\\\\ :                      ##                        ///  ::::::.',
  '                      ..:::::::.  +\\\\ .                   :##|                     /||   ..::::::::',
  '                   .......:::::..  |#|\\                   |#||                   /|#/    ......::::++',
  '                 ::...............  +##|\\                 || #                 //|#/       .......:::::.',
  '               .:......       .....   o#|\\\\               #+.#               //|##                ...::::',
  '              .....             ....   |##|\\\\ .   .       ||||- .....:     //|/#/                   ..::::.',
  '             ......                      #|\\|o\\   -o################oo-. //|/|//                    ...:++::',
  '            . +-+++:                      \\o/||####oo----|    - ----o#####o\\\\//                    ..:-oo/ :+.',
  '           ..  -\\\\\\\\\\-+++.                -o###o---   # |#|   #| #|  +- -o###\\               . .+--///-    :++:',
  '         .....       ---\\\\-+++:.        /##o/|-  |#   #| #|  |#| #   #|  o+ \\##\\       .  ./-//||        ..::++:',
  '        .......        |\\o#||oo\\-++++ -##/ - |#|  #|  #| #|  |#||#  |#   #| -+-\\#\\  .:-///|||##//        ...::++:',
  '       ........ .....     -o##|\\o||\\-o#/   #| |#  |#  o| || :|+ ||++||  #| |#/   ##//||//##/-            ....::::.',
  '        .....   .........     -\\\\|#\\##  ||.|#| o|-/ /o#|#||/ |\\\\+-oo\\\\  o|+#|://  |#||o//+         .....    ...:::.',
  '                     ..          -\\#| +\\.|# \\| ///\\/|//|//     \\|    ||  | . || /o |#|                       ..::::',
  '                                  |# \\o|# |/|| |\\ |:|  ||       |    ||  |+ |  ||+/ |#                        ..:::.',
  '        ... .                     #||++\\ ||/  /\\| | |  ||  -+-  ||   |+  |+ |.| ||+/ #| :.                    ..::::',
  '            ...     ..::-----o--o+||\\|\\ ||||//////|//  |-/|##|./\\|   ||  || || # ||//|#---oo--o------+++++:.   ..:::.',
  '             +-oo-o--o|##|##oo|o|||+|\\  /|/|//|/|//  -//|/||||/||||-- ||  || \\| |+||/+||#|#####oo||----oo-o    .....',
  '                       --------o+||\\| |  | |/ / /|||#-|/|/|||||/|//||##+   \\\\ | | ||/ | -----                   .....',
  '                                  +   | // |     |||#o#/o||/|/|/o|#||||||||     |+                              .....',
  '                                    |/ -   |/o|||||||||||\\|/|||||o----     -\\\\   |+-                             ....',
  '            .......        .....    ||-+||/|||##########|||# #|      --         |||||   ...............          ....',
  ' .                         ....... \\ --/ |||#|###########||#|#|     ooo#          -:   ......                    ....',
  ' .                          ....   |\\-/  |||||###########|||#o|   o\\     -/#o+/|        .....                    .....',
  ' .                          .....  | -..   ||||||||||||||o||#o|   +#|||||##||||  \\\\--+  ....                     ....',
  '                               .   ||||  ./|/|||||||||||||||#o|    /||||||/\\/|/    +//    .                       .',
  '                               .    --  ||/||#|o||##||\\\\- |\\#o|    |/|||||\\-//',
  '                                      \\ //|\\o#|||||\\#|    ||##|    ||#|||#.\\/     |',
  '                                   . |\\\\  |/-|||/|||||/\\---     -/\\\\|#/||.       +/. . ..  .',
  '                                    ||+     \\# |||/|#   |oo .| |#||oo|.#.       :+ | . ..  .',
  '                                   |||\\|\\-  ||||#||||://          +\\||||        /: ||',
  '                                  .|||#\\||  \\|||#o|||||             #|#+        ||  |',
  '                                  + ||#||# |##||#||| #\\\\          -/#\\#        |||  |',
  '                                   ||#||#|  \\#|||#|||# |#|/+---\\|#- #||        |#|| ||',
  '                                  ||##||#||   o|/#| |#//|/\\/--o/\\|\\o#||        |#|| -|',
  '                                   \\|\\|#||||     oo|| -|||/   .#||:#o/.       | ##||',
  '                                     ||#|||   |o|o  |   ||ooooo#||       ||   | |#|#/',
  '                                    ||#||\\|   |/###| o                 ||||   ||:##||',
  '                                    ||#\\|||   ||||-| #|:\\\\          +/|-|||    | ||||',
  '                                   ||#|||     |||\\\\\\ \\|\\\\||        ////|||       :##||',
  '                                   ||#|/      |||| ||| \\|o|     ://|/ .|||        #|||',
  '                                   |+o        /||| ||#| |/|    //|/   |||        /-|#||',
  '                               |/\\\\---++|-o||/|/ | |||| ||| ++/|//   .|||        |o\\#||',
  '                             |\\|\\//|||\\||\\||||#||| |+#| ||||||/      |\\|     |\\.\\\\  -+||',
  '                    -+ -/--\\\\ |\\-+|##||||\\|\\|  - : ||#| ||| -        |||     ||\\\\|\\\\/o\\|o+',
  '                     o--   /|o|\\##|-|#||\\\\\\\\ \\\\\\ || |o|\\|||          ||:      /\\\\+\\\\\\\\\\-||----+',
  '                        +//+//|#|/ .||\\\\\\\\\\ \\\\ ##/\\ | \\/\\||         |||   -/o|##/\\o\\||-------o|\\',
  '                           /|##|/ ///\\/|\\\\|\\/|\\|##|||---|||         |-|oo||/\\/|||/|||---\\---\\:',
  '                              |+ // |/ \\\\+\\/\\|\\\\\\|+||#/##|||||--||/o||/|||#/|/||/\\| \\\\\\',
  '                                    /   |\\ \\+||\\\\\\\\ #o|o||\\|#|+/-/o#|//-//////|/ #    \\',
  '                                      :  .\\ \\\\|\\|\\\\\\||o#o|||/||o||/|////|// /o|  |',
  '                                           |  \\|#o||o|-|//|/o|||#/|//- //   |',
  '                                                     oo\\///o#o/-+//',
]
export const LIBERTY_TINTS = [
  '',
  '                                                 1223333332  2333333321',
  '                                         12233323333333333    33333333333333331',
  '                                    1223333333333333333332 1  3333333333333333333332',
  '                                133333322222222111111111   cc   1 1111111222333333333332',
  '                             1 2333222221111        1      cc      1       111222333333321',
  '                          233  cc1322111                   cc      1            111222 ccc 332',
  '                       1233332  ccc 2                      cc                        ccc  2222221',
  '                      1122222221  ccc 1                   2ccc                     ccc   1122222222',
  '                   11111112222211  cccc                   cccc                   cccc    111111222233',
  '                 22111111111111111  ccccc                 cc c                 ccccc       1111111222221',
  '               12111111       11111   ccccc               c31c               ccccc                1112222',
  '              11111             1111   cccccc 1   1       ccccc 111112     cccccc                   1122221',
  '             111111                      cccccc   ccccccccccccccccccccc1 ccccccc                    11123322',
  '            1 cc3332                      cccccccccccccccp    p ccccccccccccccc                    112cccc 231',
  '           11  ccccccc3331                cccccccpp   p ppp   pp pp  pp cccccc               1 13cccccc    2332',
  '         11111       cccccc33321        cccccpp  pp   pp pp  ppp p   pp  pp cccc       1  1cccccc        1122332',
  '        1111111        cccccccccc3333 cccc p ppp  pp  pp pp  ppppp  pp   pp ppcccc  12ccccccccccc        11122332',
  '       11111111 11111     cccccccccccccc   pp pp  pp  pp pc 2cp cp33pp  pp ppp   cccccccccccc            111122221',
  '        11111   111111111     cccccccc  pp1ppp ppcc cccccccc ccc3ccccc  pp3pp2pp  cccccccc         11111    1112221',
  '                     11          cccc pp1pp pc ccccccccccc     cc    cc  c 1 pp pp ccc                       112222',
  '                                  cc pppp cccc cc c2c  cc       c    cc  c3 c  pppp cc                        112221',
  '        111 1                     ccpppp ccc  pcc c c  cc  ccc  cc   c3  c3 c1c pppp cc 21                    112222',
  '            111     1122cccccccccccpppp ccccppccccccc  ccccccc1ppp   cc  cc cc c ppppcccccccccccccccc3333321   112221',
  '             ccccccccccccccccccccccppp  cccppcccccc  ccccccccppppppcc cc  cc cc c3cpp3ccccccccccccccccccccc    11111',
  '                       ccccccccccccpp c  c cc c cccccccccccppppppccccccc   cc c c cpp c ccccc                   11111',
  '                                  3   c cc c     ccccccccpppppccccccccccccc     cc                              11111',
  '                                    cc c   pppppppppppppppppcccccccccc     ccc   p3c                             1111',
  '            1111111        11111    cccccppppppppppppppppppc cc      cc         ccccc   111111111111111          1111',
  ' 1                         1111111 c ccc ppppppppppppppppppcccc     cccc          c2   111111                    1111',
  ' 1                          1111   cccc  ppppppppppppppppppcccc   cc     cccc3cc        11111                    11111',
  ' 1                          11111  c c1c   pppppppppppppppccccc   ccccccccccccc  cccc3  1111                     1111',
  '                               1   cccc  ppppccpccccccccccccccc    cccccccccccc    3cc    1                       1',
  '                               1    cc  ppppccccccccccccc ccccc    ccccccccccc',
  '                                      c ppcccccccccccc    ccccc    ccccccc1cc     c',
  '                                   1 ccc  ccccccccccccccccc     ccccccccc1       3c1 1 11  1',
  '                                    ccc     cc cccccc   ccc 1c ccccccc1c1       23 c 1 11  1',
  '                                   ccccccc  ccpcccccc2cc          cccccc        c2 cc',
  '                                  1ccccccc  ccpcccccccc             ccc3        cc  c',
  '                                  c cccccc cccppcccc ccc          ccccc        ccc  c',
  '                                   ccccccc  cccpcccccc cccc3ccccccc ccc        cccc cc',
  '                                  ccccccccc   cpccc ccccccccccccccccccc        cccc cc',
  '                                   cccccccpp     cccc ccccc   cccc2ccc1       p cccc',
  '                                     cccccp   cccc  c   cccccccccc       cc   p ccccc',
  '                                    cccccpp   cccccc c                 cccc   pp2cccc',
  '                                    cccccpp   cccccc cc2cc          3cccccc    p cccc',
  '                                   cccccc     cccccc cccccc        ccccccc       2cccc',
  '                                   ccccc      cccp ccc cccc     2cccc 1ccc        cccc',
  '                                   ccc        cccp cccc ccc    cccc   ccc        cccccc',
  '                               ccccccccccccccccc p cccc ccc 33cccc   1ccc        cccccc',
  '                             ccccccccccccccccccccp c3cc ccccccc      ccc     cc1cc  c3cc',
  '                    cc cccccc ccccccccccccccc  c 2 cccc ccc c        ccc     ccccccccccccc',
  '                     ccc   cccpccccccccccccc ccc pp ccccccc          cc2      cccccccccccccccc3',
  '                        3cccppcccc cccccccc cc cccc c ccccc         ccc   cccccccccccccccccccccc',
  '                           ppcccc ccccccccccppccccccccccccc         ccccccccccccpcccccccccccc2',
  '                              cc cc cc cccccccpcccccccccccccccccccccccccccccccppccc ccc',
  '                                    c   cc ccccppcc cccccccccccccccccpppcccccppc c    c',
  '                                      2  cc cccccppccccccccpppccccccccccccc ccc  c',
  '                                           c  ccccccccccppcccccccccccc cc   c',
  '                                                     ccccccccccc3cc',
]
